### ISSUE TITLE
crash report not sync and does not create the symbol file

### ISSUE THREAD

**Issue by armanhossiny** [appmetrica/appmetrica-sdk-android#5]
### 📚 AppMetrica SDK Version

6.2.1

### 📝 Description

hi
I add a crash report code to gradle (8.5) no sync project:
![image](https://github.com/appmetrica/appmetrica-sdk-android/assets/42970068/f52dcf56-c42a-4aed-b157-a214816c2f0a)

this selected code not working 

please update doc and create example project in github 

error:
![image](https://github.com/appmetrica/appmetrica-sdk-android/assets/42970068/9e23bf31-4b8c-40b6-ad7c-e1b778dc67e5)

**Comment by KondratyonokNikita** [comment]
Hello. Thank you for reaching out. Currently, compatibility with this version of Gradle is not guaranteed. I have created a task (METRIKALIB-9403) and added it to my plan.

You probably wish for it to work right now.
* The code you highlighted in the screenshot is needed for the Gradle task to automatically invoke symbol loading after the build. Perhaps in Gradle 8.5, this is done differently. I'm confident that you will be able to find it.
* I assume that since you are enabling the NDK part of the plugin, you have native code. The issue with creating the symbol file likely lies in the change in how the path to the .so files is obtained. You can locate them in your project and specify them in the soFiles parameter.

**Comment by armanhossiny** [comment]
Thank you very much for your guidance. For about a week now, I have been trying to use SDK 6.x for crash reporting of a mobile game written with the Axmol engine(new version Cocos2dx), but the symbol file is not generated correctly. We have been using AppMetrica for two years and now we need it. Please guide me again. I tried my best but it didn't work.

**Comment by KondratyonokNikita** [comment]
To effectively address the task at hand, it is essential to have information regarding the versions of Gradle, Android Gradle Plugin (com.android.application), and the plugin (io.appmetrica.analytics:gradle). Could you kindly provide these details?

Could you specify the specific issue you are encountering? Is it related to locating .so files or initiating symbol loading?

**Comment by armanhossiny** [comment]
Hi, @KondratyonokNikita 

I temporarily fixed the issue as shown below. I hope you will fix it soon for the next version :).

I changed the AGP version to 7.4.2 and replaced  `project.tasks.configureEach` with `project.tasks.forEach` or `project.tasks.all` Then, the map file and symbol files were uploaded and crashes were detected (I didn't change Gradle, version 5.6). Overall, it doesn't work with AGP 8 or higher.
